Сделал 2 раздел
js-tasks-ru/jsbasic-20201008_vitaly-inf pull request #3
Opened 2020-10-18 14:18 UTC by blen499

2020-10-18 14:25 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция sumSalary(salaries)
+ должна складывать все зарплаты
+ должна игнорировать свойства других типов
+ должна возвращать 0 если нет свойств с зарплатами
```
```diff
Создайте калькулятор
+ должно умножа��ь числа
+ должно складывать числа
```
```diff
Определите, пуст ли объект
+ {} должен вернуть true
+ если у объекта есть хоть одно свойство, то он не пустой
+ объект с удалённым свойством - пустой
+ объект со свойством undefined должен считаться не пустым
```

Добавляю преподавателя (@stas-dolgachov) для код-ревью, посмотрим что он скажет :)

2020-10-19 10:30 UTC, stas-dolgachov requested changes

2020-10-19 10:30 UTC, stas-dolgachov commented on 2-module/1-task/index.js
> +      false;
```else { false } ```
Здесь не немет никакого смысла, удалите его, пожалуйста.

2020-10-19 10:30 UTC, stas-dolgachov commented on 2-module/3-task/index.js
> +  read(a, b) {
👍

2020-10-19 17:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @stas-dolgachov

2020-10-19 19:53 UTC, stas-dolgachov approved these changes

2020-10-19 19:53 UTC, merged